import normalize from 'react-native-normalize';
import {StyleSheet} from 'react-native';
import {Colors, FontFamily, FontSizeNormalize} from '@styles/index';
import css from './css';

export const appointmentStyles = StyleSheet.create({
  require: {
    color: Colors.main,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  title: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: css.mgV10,
  },
  txtTitle: {
    marginLeft: 10,
    fontFamily: FontFamily.nissanBold,
    fontSize: FontSizeNormalize.normal,
  },
  container: {
    paddingVertical: css.mgV10,
    paddingHorizontal: css.mgH5,
    backgroundColor: Colors.lightGray,
    flex: 1,
  },
  itemContainer: {
    // flex: 1,
    backgroundColor: Colors.lightGray,
    padding: 5,
    width: '33.33%',
  },
  itemContent: {
    padding: 20,
    borderRadius: 10,
    borderWidth: 0.5,
  },
  dateView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 5,
  },
  txtDate: {
    flex: 1,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  customer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 5,
  },
  txtName: {
    flex: 1,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  txtModel: {
    flex: 1,
    textAlign: 'right',
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  txtL: {
    textAlign: 'center',
    marginVertical: 5,
    fontFamily: FontFamily.nissanBold,
    fontSize: FontSizeNormalize.normal,
  },
  btnDetail: {
    flex: 1,
    backgroundColor: Colors.main,
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  btnReception: {
    flex: 1,
    backgroundColor: Colors.white,
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    borderWidth: 0.5,
    borderColor: Colors.main,
  },
  txtDetail: {
    color: Colors.white,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  txtReception: {
    color: Colors.main,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  state: {
    width: 30,
    height: 30,
    borderRadius: 15,
  },
  txtAdv: {
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
    marginVertical: 5,
  },
  btnContain: {flexDirection: 'row', margin: 10},
  numApp: {
    backgroundColor: Colors.white,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  nameApp: {
    backgroundColor: Colors.gray,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
    paddingHorizontal: 15,
    paddingVertical: 10,
    color: Colors.main,
  },
  content: {
    flex: 1,
    paddingVertical: css.mgV10,
    paddingHorizontal: css.mgH5,
  },
  appCon: {
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,

    elevation: 6,
  },
  inputContain: {
    flexDirection: 'row',
    paddingVertical: 10,
    alignItems: 'center',
  },
  rightTitle: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-end',
    marginHorizontal: 10,
  },
  rightTxt: {
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
    marginRight: 30,
  },
  leftTitle: {
    paddingVertical: 10,
    flex: 0.7,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  inputAddress: {flex: 3},
  txtCusRequire: {
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  cusRequireContain: {
    backgroundColor: Colors.white,
    height: 200,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    borderRadius: 5,
    marginBottom: 20,
  },
  infoContain: {
    flex: 1,
    backgroundColor: Colors.lightGray,
  },
  icon: {alignSelf: 'center', flex: 1},
  list: {marginBottom: 60, flex: 1},
  txtState: {
    textAlign: 'right',
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  fab: {
    position: 'absolute',
    margin: normalize(18),
    right: normalize(15),
    bottom: normalize(25),
    backgroundColor: Colors.main,
    height: normalize(20),
    width: normalize(20),
    justifyContent: 'center',
    alignItems: 'center',
  },
  edit: {
    position: 'absolute',
    margin: normalize(18),
    right: normalize(10),
    bottom: normalize(-3),
    backgroundColor: Colors.main,
    height: normalize(20),
    width: normalize(20),
    justifyContent: 'center',
    alignItems: 'center',
  },
  noData: {
    textAlign: 'center',
    marginVertical: normalize(5),
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  FlatList: {paddingBottom: normalize(42)},
});
