import {Dimensions, StyleSheet} from 'react-native';

import {Colors, css, FontFamily, FontSizeNormalize} from '@styles/index';

const SCREEN_WIDTH = Dimensions.get('window').width;
const SCREEN_HEIGHT = Dimensions.get('window').height;
export const progressStyle = StyleSheet.create({
  txtFl05: {
    width: SCREEN_WIDTH / 8,
    borderRightWidth: 0.5,
    borderRightColor: Colors.white,
    color: Colors.white,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.normal,
    paddingVertical: 5,
  },
  txtFl1: {
    width: (3 * SCREEN_WIDTH) / 16,
    borderRightWidth: 0.5,
    borderRightColor: Colors.white,
    color: Colors.white,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.normal,
  },
  txtFl15: {
    width: SCREEN_WIDTH / 4,
    borderRightWidth: 0.5,
    borderRightColor: Colors.white,
    color: Colors.white,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.normal,
  },
  iconSwitch: {width: 25, height: 25},
  adviserContain: {
    flex: 1.5,
    borderRightWidth: 0.5,
    borderRightColor: Colors.white,
    color: Colors.white,
    flexDirection: 'row',
    alignItems: 'center',
  },
  adviserView: {
    flex: 3,
    paddingHorizontal: 10,
  },
  containerItem: {
    flexDirection: 'row',
    paddingVertical: 5,
  },
  titleItem: {
    backgroundColor: Colors.txtGray,
    flexDirection: 'row',
  },
  txtAdv: {
    color: Colors.black,
    fontFamily: FontFamily.nissanBold,
    fontSize: FontSizeNormalize.small,
    marginVertical: 3,
    textAlign: 'center',
    borderWidth: 1,
    borderRadius: 15,
    padding: 5,
    borderColor: Colors.black,
  },
  iconContain: {flex: 1, alignItems: 'center'},
  headerModal: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    alignItems: 'center',
    padding: 5,
    borderBottomColor: Colors.black,
    borderBottomWidth: 0.5,
  },
  modal: {
    backgroundColor: Colors.white,
    alignSelf: 'center',
    width: SCREEN_WIDTH / 2,
    height: (2 * SCREEN_HEIGHT) / 3,
  },
  iconClose: {
    flex: 1,
    alignItems: 'flex-end',
  },
  titleModal: {
    flex: 5,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.normal,
    padding: 10,
  },
  txtModal: {
    color: Colors.black,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.normal,
  },
  btnChooseEmp: {
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    height: 50,
  },
  checkBox: {
    height: 25,
    width: 25,
    borderWidth: 0.5,
    borderColor: Colors.black,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 5,
  },
  btnAccept: {
    backgroundColor: Colors.colorMainButton,
    alignSelf: 'flex-end',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 5,
    borderRadius: 3,
    padding: 5,
  },
  txtAccept: {
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.normal,
    color: Colors.white,
  },
  separator: {height: 1, backgroundColor: Colors.colorText, flex: 1},
  containProgress: {
    width: SCREEN_WIDTH / 4,
    justifyContent: 'center',
    flexDirection: 'row',
  },
  progress: {
    height: 10,
    marginHorizontal: 10,
    borderRadius: 5,
    width: '80%',
  },
  txtProgress: {
    flex: 1,
    textAlignVertical: 'center',
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  progressCon: {flex: 4, justifyContent: 'center'},
  container: {
    backgroundColor: Colors.lightGray,
    paddingVertical: css.mgV10,
    paddingHorizontal: css.mgH5,
  },
  title: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: css.mgV10,
  },
  txtTitle: {
    marginLeft: 10,
    fontFamily: FontFamily.nissanBold,
    fontSize: FontSizeNormalize.normal,
  },
});
