import normalize from 'react-native-normalize';
import {StyleSheet} from 'react-native';
import {
  Colors,
  FontFamily,
  FontSizeNormalize,
  SCREEN_WIDTH,
  SCREEN_HEIGHT,
} from '@styles/index';
import css from './css';

export const receptionStyles = StyleSheet.create({
  fab: {
    position: 'absolute',
    margin: normalize(18),
    right: normalize(15),
    bottom: normalize(25),
    backgroundColor: Colors.main,
    height: normalize(20),
    width: normalize(20),
    justifyContent: 'center',
    alignItems: 'center',
  },
  require: {
    color: Colors.main,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  sigCon: {flexDirection: 'row', marginBottom: 20},
  txtCusSignature: {
    borderBottomWidth: 0.5,
    paddingVertical: 10,
    textAlign: 'center',
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
    borderBottomColor: Colors.txtGray,
  },
  titleSignature: {
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
    color: Colors.black,
    marginVertical: 10,
  },
  signatureConReceive: {
    flex: 1,
    height: 300,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 2,
    marginRight: 40,
    borderWidth: 0.2,
  },
  signatureConHanding: {
    flex: 1,
    height: 300,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 2,
    borderWidth: 0.2,
  },
  icon: {alignSelf: 'center', flex: 1},
  list: {flex: 1},
  title: {
    flexDirection: 'row',
    alignItems: 'center',
    // marginVertical: css.mgV10,
    marginVertical: normalize(5),
  },
  txtTitle: {
    marginLeft: 10,
    fontFamily: FontFamily.nissanBold,
    fontSize: FontSizeNormalize.normal,
  },
  container: {
    paddingTop: css.mgV10,
    paddingHorizontal: css.mgH5,
    backgroundColor: Colors.lightGray,
    flex: 1,
    paddingBottom: 60,
  },
  containerTab: {
    width: SCREEN_WIDTH,
    flex: 1,
    padding: 10,
  },
  itemContainer: {
    // flex: 1,
    backgroundColor: Colors.lightGray,
    padding: 5,
    width: '33.33%',
  },
  itemContent: {
    padding: 20,
    borderRadius: 10,
    backgroundColor: Colors.white,
    borderWidth: 0.5,
  },
  dateView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 5,
  },
  txtDate: {
    flex: 1,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  customer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 5,
  },
  txtName: {
    flex: 1,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  txtModel: {
    flex: 1,
    textAlign: 'right',
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  txtL: {
    textAlign: 'center',
    marginVertical: 5,
    fontFamily: FontFamily.nissanBold,
    fontSize: FontSizeNormalize.normal,
  },
  btnDetail: {
    flex: 1,
    backgroundColor: Colors.main,
    paddingVertical: 5,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  btnReception: {
    flex: 1,
    backgroundColor: Colors.white,
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    borderWidth: 0.5,
    borderColor: Colors.main,
  },
  txtDetail: {
    color: Colors.white,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  txtReception: {
    color: Colors.main,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  state: {
    width: 30,
    height: 30,
    borderRadius: 15,
  },
  txtAdv: {
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
    marginVertical: 5,
  },
  btnAdd: {
    height: normalize(50, 'height'),
    width: normalize(50, 'height'),
    backgroundColor: Colors.orange,
    position: 'absolute',
    bottom: normalize(80, 'height'),
    left: normalize(5, 'width'),
    borderRadius: normalize(25, 'height'),
    justifyContent: 'center',
    alignItems: 'center',
  },
  customerTab: {
    width: SCREEN_WIDTH,
    flex: 1,
    paddingHorizontal: 20,
    paddingBottom: 80,
  },
  checkOrderTab: {
    width: SCREEN_WIDTH,
    flex: 1,
  },
  buttonTab: {
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    width: SCREEN_WIDTH / 7,
    overflow: 'hidden',
  },
  buttonTabsCon: {
    flexDirection: 'row',
    backgroundColor: Colors.txtGray,
    paddingVertical: 5,
    // borderColor: Colors.main,
    // borderWidth: 1,
  },
  indicator: {
    backgroundColor: Colors.main,
    width: SCREEN_WIDTH / 7 + 2.5,
    position: 'absolute',
    zIndex: -1,
    ...StyleSheet.absoluteFillObject,
  },
  checkOrderContainer: {flex: 1, backgroundColor: Colors.white},
  txtTab: {
    color: Colors.white,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.normal,
  },
  numCheckOrder: {
    flex: 1,
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
    borderWidth: 0.5,
    borderColor: Colors.lightGray,
  },
  numCheckOrderCon: {
    flex: 1,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleNumCheckOder: {
    flex: 1,
    backgroundColor: Colors.lightGray,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
  },
  txtCheckOrder: {
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.normal,
    color: Colors.black,
  },
  txtReceptionName: {
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.normal,
    color: Colors.main,
  },
  inputGreyCon: {flex: 1, marginHorizontal: 20},
  licensePlateCon: {justifyContent: 'center'},
  licensePlateContainer: {
    ...css.fdR,
    flex: 1,
  },
  scannerBtn: {
    backgroundColor: Colors.main,
    padding: 10,
    width: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    marginHorizontal: 10,
  },
  scanContain: {
    flexDirection: 'row',

    paddingVertical: 20,
  },
  leftTitle: {
    paddingVertical: 10,
    flex: 0.7,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  cityCon: (disabled) => ({
    flex: 1,
    height: 40,
    borderColor: disabled ? Colors.gray : Colors.txtGray,
    borderRadius: 5,
    borderWidth: 0.5,
    justifyContent: 'center',
    backgroundColor: disabled ? Colors.gray : Colors.white,
  }),
  districtCon: (disabled) => ({
    borderColor: disabled ? Colors.gray : Colors.txtGray,
    borderRadius: 5,
    flex: 1,
    borderWidth: 0.5,
    justifyContent: 'center',
    height: 40,
    marginHorizontal: 10,
    backgroundColor: disabled ? Colors.gray : Colors.white,
  }),
  addressCon: {flexDirection: 'row', marginVertical: 10},
  txtAddress: {
    marginHorizontal: 10,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
    color: Colors.black,
  },
  streetCon: {
    flex: 3.1,
    paddingHorizontal: 1,
  },
  checkItemCon: {
    backgroundColor: Colors.white,
    marginLeft: 0,
    paddingLeft: 0,
    borderColor: '#fff',
  },
  txtCheckBox: {
    color: Colors.black,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  titleCheckOrder: {padding: 10},
  requestOfCustomerText: {
    color: Colors.black,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  txtTitleTab: {
    textAlign: 'center',
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
  },
  btnTitle: {
    paddingVertical: 3,
    paddingHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: 'white',
    borderWidth: 1,
  },
  titleTab: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
    flexDirection: 'row',
    paddingHorizontal: 10,
  },
  txtTotal: {
    color: Colors.main,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.normal,
    textAlignVertical: 'center',
    marginHorizontal: 10,
  },
  footerTab: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    flex: 1,
  },
  model: {
    borderColor: Colors.txtGray,
    flex: 1,
    justifyContent: 'center',
    height: 40,
    marginHorizontal: 10,
  },
  textModel: {
    marginRight: 30,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
    color: Colors.black,
    textAlign: 'right',
  },
  footerContain: {
    paddingVertical: 5,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.41,
    shadowRadius: 9.11,

    elevation: 14,
  },
  btnSave: {
    borderWidth: 1,
    paddingVertical: css.mgV10,
    paddingHorizontal: css.mgH10,
    borderColor: Colors.main,
    borderRadius: 5,
    backgroundColor: Colors.white,
    marginHorizontal: 10,
  },
  txtSave: {
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
    color: Colors.main,
  },
  btnUpdate: {
    borderWidth: 1,
    paddingVertical: css.mgV10,
    paddingHorizontal: css.mgH10,
    borderColor: Colors.main,
    borderRadius: 5,
    backgroundColor: Colors.main,
    marginHorizontal: 10,
  },
  txtUpdate: {
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
    color: Colors.white,
  },
  containerCreate: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  btnCreate: {
    backgroundColor: Colors.main,
    paddingVertical: 10,
    alignSelf: 'center',
    paddingHorizontal: 20,
    borderRadius: 5,
    marginVertical: 10,
  },
  warnText: {
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
    color: Colors.orange,
  },
});
export const tableCheckOrderStyles = StyleSheet.create({
  container: {width: SCREEN_WIDTH, flex: 1, padding: 10},
  title: {
    flexDirection: 'row',
    backgroundColor: Colors.txtGray,
    paddingVertical: 5,
  },
  noteContain: {
    flexDirection: 'row',
    backgroundColor: Colors.lightGray,
    paddingVertical: 5,
  },
  txtTitle: {
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
    color: Colors.white,
    textAlign: 'center',
  },
  txtOk: {
    flex: 1,
    color: Colors.black,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
    textAlign: 'center',
  },
  txtNote: {
    flex: 3,
    color: Colors.black,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
    textAlign: 'center',
  },
  checkBoxItem: {
    width: 30,
    height: 30,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,

    elevation: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemName: {
    flex: 2,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
    color: Colors.black,
  },
  itemReception: {flex: 1, flexDirection: 'row', alignItems: 'center'},
  checkBox: {
    flex: 1,
    padding: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemContain: {
    flexDirection: 'row',
    paddingVertical: 3,
    alignItems: 'center',
  },
  inputCon: {
    flex: 3,
    height: 30,
  },
  okTitle: {flexDirection: 'row', flex: 1},
});
export const vehicleBodyStyle = StyleSheet.create({
  checkOrderTab: {
    width: SCREEN_WIDTH,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imgVehicle: {height: '100%', width: '60%'},
  noteCon: {
    width: '40%',
    backgroundColor: Colors.lightGray,
  },
  itemContain: {
    flex: 1,
    backgroundColor: Colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    margin: 5,
    borderRadius: 10,
    padding: 3,
  },
  iconContain: {
    backgroundColor: Colors.lightGray,
    padding: 5,
    borderRadius: 10,
  },
  icon: {width: 40, height: 40},
  txtNote: {
    color: Colors.black,
    fontFamily: FontFamily.nissanRegular,
    fontSize: FontSizeNormalize.small,
    marginLeft: 10,
  },
  txtErr: {
    color: Colors.black,
    fontFamily: FontFamily.nissanBold,
    fontSize: FontSizeNormalize.normal,
    marginLeft: 10,
  },
  bgImg: {
    width: SCREEN_WIDTH / 2,
    height: SCREEN_HEIGHT / 2,
    alignSelf: 'center',
  },
  btnReload: {
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 20,
  },
  btnContain: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  txtNoImage: {
    color: Colors.black,
    fontFamily: FontFamily.nissanBold,
    fontSize: FontSizeNormalize.small,
    textAlign: 'center',
  },
});

export const modalCheckOrderSty = StyleSheet.create({
  contentError: {
    padding: 10,
  },
  content: {
    backgroundColor: Colors.white,
    width: SCREEN_WIDTH * 0.75,
    maxHeight: SCREEN_HEIGHT * 0.9,
    minHeight: SCREEN_HEIGHT * 0.3,
  },
  headerCon: {
    height: 55,
    backgroundColor: Colors.main,
    paddingLeft: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  textHeader: {
    fontFamily: FontFamily.nissanBold,
    fontSize: FontSizeNormalize.normal,
    color: Colors.white,
  },
  button: {
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    width: SCREEN_WIDTH / 8,
    alignSelf: 'flex-end',
    borderRadius: 6,
    backgroundColor: Colors.main,
    position: 'absolute',
    bottom: 10,
    right: 10,
  },
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  btnContain: {
    flexDirection: 'row',
    position: 'absolute',
    bottom: 10,
    right: 5,
  },
  btn: {
    backgroundColor: Colors.main,
    alignItems: 'center',
    marginHorizontal: 10,
    paddingVertical: 5,
    paddingHorizontal: 10,
    justifyContent: 'center',
    borderRadius: 10,
  },
  txtContent: {
    fontFamily: FontFamily.nissanBold,
    fontSize: FontSizeNormalize.normal,
    color: Colors.black,
    paddingHorizontal: 5,
  },
});
export const receptionDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
});
