require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'nissan_service_mobile' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-print', :path => '../node_modules/react-native-print'

  pod 'react-native-html-to-pdf', :path => '../node_modules/react-native-html-to-pdf'

  target 'nissan_service_mobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'nissan_service_mobile-tvOS' do
  # Pods for nissan_service_mobile-tvOS

  target 'nissan_service_mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
